import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // Node.js scripts use console / process without imports.
  {
    files: ["scripts/**/*.mjs", "scripts/**/*.js"],
    languageOptions: {
      globals: {
        console: "readonly",
        process: "readonly",
      },
    },
  },
  {
    ignores: [
      ".next/",
      "node_modules/",
      "prisma/",
      // Auto-generated by Next.js; contains triple-slash references by design.
      "next-env.d.ts",
    ],
  }
);
